

security:
  basic:
  enabled: false

server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

zuul:
  routes:
    user-service: /users/**
    #songervice: /songs/**
    ignored-services: '*'
  sensitive-headers: Cookie, Set-Cookie


#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.itemsharing: DEBUG